{
  "Header": {
    "Original": "CVE-2025-4948 (A flaw was found in the soup_multipart_new_from_message() function of  ...)",
    "ID": "CVE-2025-4948",
    "Description": "(A flaw was found in the soup_multipart_new_from_message() function of  ...)"
  },
  "Annotations": [
    {
      "Original": "- libsoup3 \u003cunfixed\u003e (bug #1106204)",
      "Type": "package",
      "Package": "libsoup3",
      "Kind": "unfixed",
      "BugNo": 1106204
    },
    {
      "Original": "- libsoup2.4 \u003cunfixed\u003e (bug #1106337)",
      "Type": "package",
      "Package": "libsoup2.4",
      "Kind": "unfixed",
      "BugNo": 1106337
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/issues/449",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/issues/449"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/463",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/463"
    }
  ]
}